name: Keep Alive HF Space
on:
  schedule:
    - cron: "*/10 * * * *"  # Ye har 10 minute me jagayega
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Wake up Hugging Face Spaces (Ultimate Version)
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # The Corrected URL Format (Lowercase and Hyphens)
          echo "Pinging Autofilter Bot 1..."
          curl -L -H "Authorization: Bearer $HF_TOKEN" -H "User-Agent: Mozilla/5.0" https://sona55-my-fuzzy-c-bot.hf.space/
          
          echo "Pinging Autofilter Bot 2..."
          curl -L -H "Authorization: Bearer $HF_TOKEN" -H "User-Agent: Mozilla/5.0" https://sona55-my-fuzzy-c-22-bot.hf.space/
