name: Keep Alive HF Space
on:
  schedule:
    - cron: "*/10 * * * *"  # Ye har 10 minute me jagayega
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Wake up Hugging Face Spaces (Ultimate Version)
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          echo "Pinging Autofilter Bot 1..."
          curl -i -L -H "Authorization: Bearer $HF_TOKEN" -H "User-Agent: Mozilla/5.0" https://huggingface.co/spaces/Sona55/My_fuzzy_c_bot
          
          echo "Pinging Autofilter Bot 2..."
          # Niche wale URL me apne second bot ke space ka sahi naam daal lijiyega
          curl -i -L -H "Authorization: Bearer $HF_TOKEN" -H "User-Agent: Mozilla/5.0" https://huggingface.co/spaces/Sona55/My_fuzzy_c_22_bot
